### ISSUE TITLE
Scikit-learn 버전이 안 맞아서 에러가 발생

### ISSUE THREAD

**Issue by sigmadream** [Nam-JoonKyu/MaskCheck#2]
SVM 모델의 경우 0.20.2 버전에서 만든 pkl 이라서 에러가 발생하는 듯 하네요. 0.23.2로 버전 업데이트해서 pkl 파일을 플라토에 업로드해주세요.

> https://github.com/Nam-JoonKyu/MaskCheck/blob/8949f07f4f69eeaab9a98a0145d7d30f6d1c082f/pyqt.py#L79

![image](https://user-images.githubusercontent.com/553900/104694770-0605ac00-574f-11eb-9d69-e473f276204f.png)

**Comment by Nam-JoonKyu** [comment]
대용량 첨부 파일은 30일간 보관 / 100회까지 다운로드 가능




남준규_프로젝트_수정본.zip 214MB


  다운로드 기간: 2021/01/15 ~ 2021/02/14






교수님 안녕하십니까?
프로젝트 관련해서 메일 드립니다.
 
교수님께서 말씀하신대로 수정한 뒤 플라토에 업로드하려 하였으나 제출기한이 마감되어 메일로 압축파일을 보내드리도록 하겠습니다.
 
24 line에서 발생한 오류는 제가 파일 압축시 masknet.ckpt 파일명을 masknet_separable.ckpt 로 변경해서 발생한 것 같습니다.
그래서 코드에서 load부분 파일명만 수정하고, SVM모델도 0.23.2로 업데이트 한 이후 다시 보냅니다.
 
감사합니다.
 
-----Original Message-----

**Comment by sigmadream** [comment]
감사합니다. 수정된 내용을 바탕으로 성적에 반영하도록 하겠습니다.

즐거운 방학되세요!


2021년 1월 15일 (금) 오후 5:03, Nam-JoonKyu <notifications@github.com>님이 작성:
